pages = [{"l":"index.html","n":"Compile Time LL1 Parser","t":"Compile Time LL1 Parser","d":"","k":"static"},
{"l":"ll1compiletime.html","n":"ll1compiletime","t":"package ll1compiletime","d":"ll1compiletime","k":"package"},
{"l":"ll1compiletime.html","n":"CompileTime","t":"type CompileTime[A, T, K] = CompileTime[A, T, K]","d":"ll1compiletime","k":"type"},
{"l":"ll1compiletime.html","n":"SyntaxDefinition","t":"type SyntaxDefinition[T, K] = SyntaxDefinition[T, K]","d":"ll1compiletime","k":"type"},
{"l":"ll1compiletime.html","n":"buildParsingTable","t":"def buildParsingTable[K](parser: CompileTime[_, _, K]): PartialParsingTable[K]","d":"ll1compiletime","k":"def"},
{"l":"ll1compiletime/ParsingResult.html","n":"ParsingResult","t":"trait ParsingResult[A]","d":"ll1compiletime/ParsingResult","k":"trait"},
{"l":"ll1compiletime/ParsingResult.html","n":"toType","t":"def toType[B]: ParsingResult[B]","d":"ll1compiletime/ParsingResult","k":"def"},
{"l":"ll1compiletime/ParsingResult$.html","n":"ParsingResult","t":"object ParsingResult","d":"ll1compiletime/ParsingResult$","k":"object"},
{"l":"ll1compiletime/ParsingResult$$ParsedSuccessfully.html","n":"ParsedSuccessfully","t":"class ParsedSuccessfully[A](v: A) extends ParsingResult[A]","d":"ll1compiletime/ParsingResult$$ParsedSuccessfully","k":"class"},
{"l":"ll1compiletime/ParsingResult$$ParsedSuccessfully.html","n":"toType","t":"def toType[B]: ParsingResult[B]","d":"ll1compiletime/ParsingResult$$ParsedSuccessfully","k":"def"},
{"l":"ll1compiletime/ParsingResult$$ParsedSuccessfullyWithRest.html","n":"ParsedSuccessfullyWithRest","t":"class ParsedSuccessfullyWithRest[A, Token](v: A, tokens: List[Token]) extends ParsingResult[A]","d":"ll1compiletime/ParsingResult$$ParsedSuccessfullyWithRest","k":"class"},
{"l":"ll1compiletime/ParsingResult$$ParsedSuccessfullyWithRest.html","n":"toType","t":"def toType[B]: ParsingResult[B]","d":"ll1compiletime/ParsingResult$$ParsedSuccessfullyWithRest","k":"def"},
{"l":"ll1compiletime/ParsingResult$$UnexpectedEnd.html","n":"UnexpectedEnd","t":"class UnexpectedEnd[A, Kind](expected: Set[Kind]) extends ParsingResult[A]","d":"ll1compiletime/ParsingResult$$UnexpectedEnd","k":"class"},
{"l":"ll1compiletime/ParsingResult$$UnexpectedEnd.html","n":"toType","t":"def toType[B]: ParsingResult[B]","d":"ll1compiletime/ParsingResult$$UnexpectedEnd","k":"def"},
{"l":"ll1compiletime/ParsingResult$$UnexpectedToken.html","n":"UnexpectedToken","t":"class UnexpectedToken[A, Kind](k: Kind, expected: Set[Kind]) extends ParsingResult[A]","d":"ll1compiletime/ParsingResult$$UnexpectedToken","k":"class"},
{"l":"ll1compiletime/ParsingResult$$UnexpectedToken.html","n":"toType","t":"def toType[B]: ParsingResult[B]","d":"ll1compiletime/ParsingResult$$UnexpectedToken","k":"def"},
{"l":"ll1compiletime/~.html","n":"~","t":"class ~[+A, +B](_1: A, _2: B)","d":"ll1compiletime/~","k":"class"},
{"l":"ll1compiletime/~.html","n":"~","t":"def ~[C](next: C): A ~ B ~ C","d":"ll1compiletime/~","k":"def"},
{"l":"ll1compiletime/parser.html","n":"ll1compiletime.parser","t":"package ll1compiletime.parser","d":"ll1compiletime/parser","k":"package"},
{"l":"ll1compiletime/parser/ParsingTable.html","n":"ParsingTable","t":"class ParsingTable[A, Token, Kind]","d":"ll1compiletime/parser/ParsingTable","k":"class"},
{"l":"ll1compiletime/parser/ParsingTable.html","n":"apply","t":"def apply(tokens: Iterator[Token]): ParsingResult[A]","d":"ll1compiletime/parser/ParsingTable","k":"def"},
{"l":"ll1compiletime/parser/PartialParsingTable.html","n":"PartialParsingTable","t":"class PartialParsingTable[Kind](entry: Int, table: Map[(Int, Kind), SymboleType], nullable: Map[Int, Nullable])","d":"ll1compiletime/parser/PartialParsingTable","k":"class"},
{"l":"ll1compiletime/parser/PartialParsingTable$.html","n":"PartialParsingTable","t":"object PartialParsingTable","d":"ll1compiletime/parser/PartialParsingTable$","k":"object"},
{"l":"ll1compiletime/parser/PartialParsingTable$.html","n":"PartialParsingTableToExpr","t":"given PartialParsingTableToExpr[Kind : ToExpr]: PartialParsingTableToExpr[Kind]","d":"ll1compiletime/parser/PartialParsingTable$","k":"given"},
{"l":"ll1compiletime/syntax.html","n":"ll1compiletime.syntax","t":"package ll1compiletime.syntax","d":"ll1compiletime/syntax","k":"package"},
{"l":"ll1compiletime/syntax/CompileTime.html","n":"CompileTime","t":"trait CompileTime[A, T, K]","d":"ll1compiletime/syntax/CompileTime","k":"trait"},
{"l":"ll1compiletime/syntax/CompileTime.html","n":"CSyntax","t":"type CSyntax[X] = Syntax[X, Token, Kind]","d":"ll1compiletime/syntax/CompileTime","k":"type"},
{"l":"ll1compiletime/syntax/CompileTime.html","n":"Kind","t":"type Kind = K","d":"ll1compiletime/syntax/CompileTime","k":"type"},
{"l":"ll1compiletime/syntax/CompileTime.html","n":"Token","t":"type Token = T","d":"ll1compiletime/syntax/CompileTime","k":"type"},
{"l":"ll1compiletime/syntax/CompileTime.html","n":"entryPoint","t":"val entryPoint: CSyntax[A]","d":"ll1compiletime/syntax/CompileTime","k":"val"},
{"l":"ll1compiletime/syntax/CompileTime.html","n":"getKind","t":"def getKind(t: Token): Kind","d":"ll1compiletime/syntax/CompileTime","k":"def"},
{"l":"ll1compiletime/syntax/CompileTime.html","n":"macroCall","t":"def macroCall: PartialParsingTable[Kind]","d":"ll1compiletime/syntax/CompileTime","k":"def"},
{"l":"ll1compiletime/syntax/CompileTime.html","n":"parser","t":"def parser: ParsingTable[A, T, Kind]","d":"ll1compiletime/syntax/CompileTime","k":"def"},
{"l":"ll1compiletime/syntax/SyntaxDefinition.html","n":"SyntaxDefinition","t":"trait SyntaxDefinition[T, K]","d":"ll1compiletime/syntax/SyntaxDefinition","k":"trait"},
{"l":"ll1compiletime/syntax/SyntaxDefinition.html","n":"+:","t":"def +:[X]: CSyntax[Seq[X]]","d":"ll1compiletime/syntax/SyntaxDefinition","k":"def"},
{"l":"ll1compiletime/syntax/SyntaxDefinition.html","n":":+","t":"def :+(that: CSyntax[X]): CSyntax[Seq[X]]","d":"ll1compiletime/syntax/SyntaxDefinition","k":"def"},
{"l":"ll1compiletime/syntax/SyntaxDefinition.html","n":"CSyntax","t":"type CSyntax[X] = Syntax[X, Token, Kind]","d":"ll1compiletime/syntax/SyntaxDefinition","k":"type"},
{"l":"ll1compiletime/syntax/SyntaxDefinition.html","n":"Kind","t":"type Kind = K","d":"ll1compiletime/syntax/SyntaxDefinition","k":"type"},
{"l":"ll1compiletime/syntax/SyntaxDefinition.html","n":"Token","t":"type Token = T","d":"ll1compiletime/syntax/SyntaxDefinition","k":"type"},
{"l":"ll1compiletime/syntax/SyntaxDefinition.html","n":"accept","t":"def accept[B](k: Kind)(f: PartialFunction[Token, B])(using IdCounter): CSyntax[B]","d":"ll1compiletime/syntax/SyntaxDefinition","k":"def"},
{"l":"ll1compiletime/syntax/SyntaxDefinition.html","n":"elem","t":"def elem(k: Kind)(using IdCounter): CSyntax[Token]","d":"ll1compiletime/syntax/SyntaxDefinition","k":"def"},
{"l":"ll1compiletime/syntax/SyntaxDefinition.html","n":"epsilon","t":"def epsilon[B](e: B)(using IdCounter): CSyntax[B]","d":"ll1compiletime/syntax/SyntaxDefinition","k":"def"},
{"l":"ll1compiletime/syntax/SyntaxDefinition.html","n":"failure","t":"def failure[B](using IdCounter): CSyntax[B]","d":"ll1compiletime/syntax/SyntaxDefinition","k":"def"},
{"l":"ll1compiletime/syntax/SyntaxDefinition.html","n":"getKind","t":"def getKind(t: Token): Kind","d":"ll1compiletime/syntax/SyntaxDefinition","k":"def"},
{"l":"ll1compiletime/syntax/SyntaxDefinition.html","n":"idc","t":"given idc: IdCounter","d":"ll1compiletime/syntax/SyntaxDefinition","k":"given"},
{"l":"ll1compiletime/syntax/SyntaxDefinition.html","n":"many","t":"def many[A](rep: CSyntax[A])(using IdCounter): CSyntax[Seq[A]]","d":"ll1compiletime/syntax/SyntaxDefinition","k":"def"},
{"l":"ll1compiletime/syntax/SyntaxDefinition.html","n":"many1","t":"def many1[A](rep: CSyntax[A])(using IdCounter): CSyntax[Seq[A]]","d":"ll1compiletime/syntax/SyntaxDefinition","k":"def"},
{"l":"ll1compiletime/syntax/SyntaxDefinition.html","n":"map","t":"def map[B](f: X => B): CSyntax[B]","d":"ll1compiletime/syntax/SyntaxDefinition","k":"def"},
{"l":"ll1compiletime/syntax/SyntaxDefinition.html","n":"oneOf","t":"def oneOf[A](syntaxes: CSyntax[A]*)(using IdCounter): CSyntax[A]","d":"ll1compiletime/syntax/SyntaxDefinition","k":"def"},
{"l":"ll1compiletime/syntax/SyntaxDefinition.html","n":"opt","t":"def opt[B](cs: CSyntax[B]): CSyntax[Option[B]]","d":"ll1compiletime/syntax/SyntaxDefinition","k":"def"},
{"l":"ll1compiletime/syntax/SyntaxDefinition.html","n":"recursive","t":"def recursive[B](syntax: => CSyntax[B])(using IdCounter): CSyntax[B]","d":"ll1compiletime/syntax/SyntaxDefinition","k":"def"},
{"l":"ll1compiletime/syntax/SyntaxDefinition.html","n":"rep1sep","t":"def rep1sep[A, B](rep: CSyntax[A], sep: CSyntax[B])(using IdCounter): CSyntax[Seq[A]]","d":"ll1compiletime/syntax/SyntaxDefinition","k":"def"},
{"l":"ll1compiletime/syntax/SyntaxDefinition.html","n":"repsep","t":"def repsep[A, B](rep: CSyntax[A], sep: CSyntax[B])(using IdCounter): CSyntax[Seq[A]]","d":"ll1compiletime/syntax/SyntaxDefinition","k":"def"},
{"l":"ll1compiletime/syntax/SyntaxDefinition.html","n":"up","t":"def up[B >: X]: CSyntax[B]","d":"ll1compiletime/syntax/SyntaxDefinition","k":"def"},
{"l":"ll1compiletime/syntax/SyntaxDefinition.html","n":"|","t":"def |(that: CSyntax[X])(using IdCounter): CSyntax[X]","d":"ll1compiletime/syntax/SyntaxDefinition","k":"def"},
{"l":"ll1compiletime/syntax/SyntaxDefinition.html","n":"||","t":"def ||[B](that: CSyntax[B])(using IdCounter): CSyntax[Either[X, B]]","d":"ll1compiletime/syntax/SyntaxDefinition","k":"def"},
{"l":"ll1compiletime/syntax/SyntaxDefinition.html","n":"~","t":"def ~[B](that: CSyntax[B]): CSyntax[X ~ B]","d":"ll1compiletime/syntax/SyntaxDefinition","k":"def"},
{"l":"ll1compiletime/syntax/SyntaxDefinition.html","n":"~<~","t":"def ~<~[B](that: CSyntax[B]): CSyntax[X]","d":"ll1compiletime/syntax/SyntaxDefinition","k":"def"},
{"l":"ll1compiletime/syntax/SyntaxDefinition.html","n":"~>~","t":"def ~>~[B](that: CSyntax[B]): CSyntax[B]","d":"ll1compiletime/syntax/SyntaxDefinition","k":"def"},
{"l":"docs/index.html","n":"Compile Time LL1 Parser","t":"Compile Time LL1 Parser","d":"","k":"static"}];