pages = [{"l":"index.html#","e":false,"i":"","n":"comptime-ll1-parser-gen","t":"comptime-ll1-parser-gen","d":"","k":"static"},
{"l":"ll1compiletime.html#","e":false,"i":"","n":"ll1compiletime","t":"ll1compiletime","d":"","k":"package"},
{"l":"ll1compiletime.html#CompileTime-0","e":false,"i":"","n":"CompileTime","t":"CompileTime[A, T, K] = CompileTime[A, T, K]","d":"ll1compiletime","k":"type"},
{"l":"ll1compiletime.html#SyntaxDefinition-0","e":false,"i":"","n":"SyntaxDefinition","t":"SyntaxDefinition[T, K] = SyntaxDefinition[T, K]","d":"ll1compiletime","k":"type"},
{"l":"ll1compiletime.html#buildParsingTable-fffff32c","e":false,"i":"","n":"buildParsingTable","t":"buildParsingTable[K](parser: CompileTime[_, _, K]): PartialParsingTable[K]","d":"ll1compiletime","k":"def"},
{"l":"ll1compiletime/ParsingResult.html#","e":false,"i":"","n":"ParsingResult","t":"ParsingResult[A]","d":"ll1compiletime","k":"trait"},
{"l":"ll1compiletime/ParsingResult.html#toType-ffffffff","e":false,"i":"","n":"toType","t":"toType[B]: ParsingResult[B]","d":"ll1compiletime.ParsingResult","k":"def"},
{"l":"ll1compiletime/ParsingResult$.html#","e":false,"i":"","n":"ParsingResult","t":"ParsingResult","d":"ll1compiletime","k":"object"},
{"l":"ll1compiletime/ParsingResult$$ParsedSuccessfully.html#","e":false,"i":"","n":"ParsedSuccessfully","t":"ParsedSuccessfully[A](v: A) extends ParsingResult[A]","d":"ll1compiletime.ParsingResult","k":"class"},
{"l":"ll1compiletime/ParsingResult$$ParsedSuccessfully.html#toType-ffffffff","e":false,"i":"","n":"toType","t":"toType[B]: ParsingResult[B]","d":"ll1compiletime.ParsingResult.ParsedSuccessfully","k":"def"},
{"l":"ll1compiletime/ParsingResult$$ParsedSuccessfullyWithRest.html#","e":false,"i":"","n":"ParsedSuccessfullyWithRest","t":"ParsedSuccessfullyWithRest[A, Token](v: A, tokens: List[Token]) extends ParsingResult[A]","d":"ll1compiletime.ParsingResult","k":"class"},
{"l":"ll1compiletime/ParsingResult$$ParsedSuccessfullyWithRest.html#toType-ffffffff","e":false,"i":"","n":"toType","t":"toType[B]: ParsingResult[B]","d":"ll1compiletime.ParsingResult.ParsedSuccessfullyWithRest","k":"def"},
{"l":"ll1compiletime/ParsingResult$$UnexpectedEnd.html#","e":false,"i":"","n":"UnexpectedEnd","t":"UnexpectedEnd[A, Kind](expected: Set[Kind]) extends ParsingResult[A]","d":"ll1compiletime.ParsingResult","k":"class"},
{"l":"ll1compiletime/ParsingResult$$UnexpectedEnd.html#toType-ffffffff","e":false,"i":"","n":"toType","t":"toType[B]: ParsingResult[B]","d":"ll1compiletime.ParsingResult.UnexpectedEnd","k":"def"},
{"l":"ll1compiletime/ParsingResult$$UnexpectedToken.html#","e":false,"i":"","n":"UnexpectedToken","t":"UnexpectedToken[A, Kind](k: Kind, expected: Set[Kind]) extends ParsingResult[A]","d":"ll1compiletime.ParsingResult","k":"class"},
{"l":"ll1compiletime/ParsingResult$$UnexpectedToken.html#toType-ffffffff","e":false,"i":"","n":"toType","t":"toType[B]: ParsingResult[B]","d":"ll1compiletime.ParsingResult.UnexpectedToken","k":"def"},
{"l":"ll1compiletime/~.html#","e":false,"i":"","n":"~","t":"~[+A, +B](_1: A, _2: B)","d":"ll1compiletime","k":"class"},
{"l":"ll1compiletime/~.html#~-643","e":false,"i":"","n":"~","t":"~[C](next: C): A ~ B ~ C","d":"ll1compiletime.~","k":"def"},
{"l":"ll1compiletime/parser.html#","e":false,"i":"","n":"ll1compiletime.parser","t":"ll1compiletime.parser","d":"","k":"package"},
{"l":"ll1compiletime/parser/ParsingTable.html#","e":false,"i":"","n":"ParsingTable","t":"ParsingTable[A, Token, Kind]","d":"ll1compiletime.parser","k":"class"},
{"l":"ll1compiletime/parser/ParsingTable.html#apply-784","e":false,"i":"","n":"apply","t":"apply(tokens: Iterator[Token]): ParsingResult[A]","d":"ll1compiletime.parser.ParsingTable","k":"def"},
{"l":"ll1compiletime/parser/PartialParsingTable.html#","e":false,"i":"","n":"PartialParsingTable","t":"PartialParsingTable[Kind](entry: Int, table: Map[(Int, Kind), SymboleType], nullable: Map[Int, Nullable])","d":"ll1compiletime.parser","k":"class"},
{"l":"ll1compiletime/parser/PartialParsingTable$.html#","e":false,"i":"","n":"PartialParsingTable","t":"PartialParsingTable","d":"ll1compiletime.parser","k":"object"},
{"l":"ll1compiletime/parser/PartialParsingTable$.html#PartialParsingTableToExpr-5fd","e":false,"i":"","n":"PartialParsingTableToExpr","t":"PartialParsingTableToExpr[Kind : ToExpr]: PartialParsingTableToExpr[Kind]","d":"ll1compiletime.parser.PartialParsingTable","k":"given"},
{"l":"ll1compiletime/syntax.html#","e":false,"i":"","n":"ll1compiletime.syntax","t":"ll1compiletime.syntax","d":"","k":"package"},
{"l":"ll1compiletime/syntax/CompileTime.html#","e":false,"i":"","n":"CompileTime","t":"CompileTime[A, T, K]","d":"ll1compiletime.syntax","k":"trait"},
{"l":"ll1compiletime/syntax/CompileTime.html#CSyntax-0","e":false,"i":"","n":"CSyntax","t":"CSyntax[X] = Syntax[X, Token, Kind]","d":"ll1compiletime.syntax.CompileTime","k":"type"},
{"l":"ll1compiletime/syntax/CompileTime.html#Kind-0","e":false,"i":"","n":"Kind","t":"Kind = K","d":"ll1compiletime.syntax.CompileTime","k":"type"},
{"l":"ll1compiletime/syntax/CompileTime.html#Token-0","e":false,"i":"","n":"Token","t":"Token = T","d":"ll1compiletime.syntax.CompileTime","k":"type"},
{"l":"ll1compiletime/syntax/CompileTime.html#entryPoint-0","e":false,"i":"","n":"entryPoint","t":"entryPoint: CSyntax[A]","d":"ll1compiletime.syntax.CompileTime","k":"val"},
{"l":"ll1compiletime/syntax/CompileTime.html#getKind-d26","e":false,"i":"","n":"getKind","t":"getKind(t: Token): Kind","d":"ll1compiletime.syntax.CompileTime","k":"def"},
{"l":"ll1compiletime/syntax/CompileTime.html#macroCall-0","e":false,"i":"","n":"macroCall","t":"macroCall: PartialParsingTable[Kind]","d":"ll1compiletime.syntax.CompileTime","k":"def"},
{"l":"ll1compiletime/syntax/CompileTime.html#parser-0","e":false,"i":"","n":"parser","t":"parser: ParsingTable[A, T, Kind]","d":"ll1compiletime.syntax.CompileTime","k":"def"},
{"l":"ll1compiletime/syntax/SyntaxDefinition.html#","e":false,"i":"","n":"SyntaxDefinition","t":"SyntaxDefinition[T, K]","d":"ll1compiletime.syntax","k":"trait"},
{"l":"ll1compiletime/syntax/SyntaxDefinition.html#+:-fffffafe","e":false,"i":"CSyntax[X]","n":"+:","t":"+:[X]: CSyntax[Seq[X]]","d":"ll1compiletime.syntax.SyntaxDefinition","k":"def"},
{"l":"ll1compiletime/syntax/SyntaxDefinition.html#:+-fffffafe","e":false,"i":"CSyntax[Seq[X]]","n":":+","t":":+(that: CSyntax[X]): CSyntax[Seq[X]]","d":"ll1compiletime.syntax.SyntaxDefinition","k":"def"},
{"l":"ll1compiletime/syntax/SyntaxDefinition.html#CSyntax-0","e":false,"i":"","n":"CSyntax","t":"CSyntax[X] = Syntax[X, Token, Kind]","d":"ll1compiletime.syntax.SyntaxDefinition","k":"type"},
{"l":"ll1compiletime/syntax/SyntaxDefinition.html#Kind-0","e":false,"i":"","n":"Kind","t":"Kind = K","d":"ll1compiletime.syntax.SyntaxDefinition","k":"type"},
{"l":"ll1compiletime/syntax/SyntaxDefinition.html#Token-0","e":false,"i":"","n":"Token","t":"Token = T","d":"ll1compiletime.syntax.SyntaxDefinition","k":"type"},
{"l":"ll1compiletime/syntax/SyntaxDefinition.html#accept-4b7","e":false,"i":"","n":"accept","t":"accept[B](k: Kind)(f: PartialFunction[Token, B])(using IdCounter): CSyntax[B]","d":"ll1compiletime.syntax.SyntaxDefinition","k":"def"},
{"l":"ll1compiletime/syntax/SyntaxDefinition.html#elem-fffff9d1","e":false,"i":"","n":"elem","t":"elem(k: Kind)(using IdCounter): CSyntax[Token]","d":"ll1compiletime.syntax.SyntaxDefinition","k":"def"},
{"l":"ll1compiletime/syntax/SyntaxDefinition.html#epsilon-fffff900","e":false,"i":"","n":"epsilon","t":"epsilon[B](e: B)(using IdCounter): CSyntax[B]","d":"ll1compiletime.syntax.SyntaxDefinition","k":"def"},
{"l":"ll1compiletime/syntax/SyntaxDefinition.html#failure-873","e":false,"i":"","n":"failure","t":"failure[B](using IdCounter): CSyntax[B]","d":"ll1compiletime.syntax.SyntaxDefinition","k":"def"},
{"l":"ll1compiletime/syntax/SyntaxDefinition.html#getKind-d26","e":false,"i":"","n":"getKind","t":"getKind(t: Token): Kind","d":"ll1compiletime.syntax.SyntaxDefinition","k":"def"},
{"l":"ll1compiletime/syntax/SyntaxDefinition.html#idc-0","e":false,"i":"","n":"idc","t":"idc: IdCounter","d":"ll1compiletime.syntax.SyntaxDefinition","k":"given"},
{"l":"ll1compiletime/syntax/SyntaxDefinition.html#many-1a4","e":false,"i":"","n":"many","t":"many[A](rep: CSyntax[A])(using IdCounter): CSyntax[Seq[A]]","d":"ll1compiletime.syntax.SyntaxDefinition","k":"def"},
{"l":"ll1compiletime/syntax/SyntaxDefinition.html#many1-1a4","e":false,"i":"","n":"many1","t":"many1[A](rep: CSyntax[A])(using IdCounter): CSyntax[Seq[A]]","d":"ll1compiletime.syntax.SyntaxDefinition","k":"def"},
{"l":"ll1compiletime/syntax/SyntaxDefinition.html#map-acf","e":false,"i":"CSyntax[X]","n":"map","t":"map[B](f: X => B): CSyntax[B]","d":"ll1compiletime.syntax.SyntaxDefinition","k":"def"},
{"l":"ll1compiletime/syntax/SyntaxDefinition.html#oneOf-b28","e":false,"i":"","n":"oneOf","t":"oneOf[A](syntaxes: CSyntax[A]*)(using IdCounter): CSyntax[A]","d":"ll1compiletime.syntax.SyntaxDefinition","k":"def"},
{"l":"ll1compiletime/syntax/SyntaxDefinition.html#opt-fffffe8f","e":false,"i":"","n":"opt","t":"opt[B](cs: CSyntax[B]): CSyntax[Option[B]]","d":"ll1compiletime.syntax.SyntaxDefinition","k":"def"},
{"l":"ll1compiletime/syntax/SyntaxDefinition.html#recursive-ba5","e":false,"i":"","n":"recursive","t":"recursive[B](syntax: => CSyntax[B])(using IdCounter): CSyntax[B]","d":"ll1compiletime.syntax.SyntaxDefinition","k":"def"},
{"l":"ll1compiletime/syntax/SyntaxDefinition.html#rep1sep-fffff9b4","e":false,"i":"","n":"rep1sep","t":"rep1sep[A, B](rep: CSyntax[A], sep: CSyntax[B])(using IdCounter): CSyntax[Seq[A]]","d":"ll1compiletime.syntax.SyntaxDefinition","k":"def"},
{"l":"ll1compiletime/syntax/SyntaxDefinition.html#repsep-fffff9b4","e":false,"i":"","n":"repsep","t":"repsep[A, B](rep: CSyntax[A], sep: CSyntax[B])(using IdCounter): CSyntax[Seq[A]]","d":"ll1compiletime.syntax.SyntaxDefinition","k":"def"},
{"l":"ll1compiletime/syntax/SyntaxDefinition.html#up-fffff400","e":false,"i":"CSyntax[X]","n":"up","t":"up[B >: X]: CSyntax[B]","d":"ll1compiletime.syntax.SyntaxDefinition","k":"def"},
{"l":"ll1compiletime/syntax/SyntaxDefinition.html#|-755","e":false,"i":"CSyntax[X]","n":"|","t":"|(that: CSyntax[X])(using ic: IdCounter): CSyntax[X]","d":"ll1compiletime.syntax.SyntaxDefinition","k":"def"},
{"l":"ll1compiletime/syntax/SyntaxDefinition.html#||-fffff744","e":false,"i":"CSyntax[X]","n":"||","t":"||[B](that: CSyntax[B])(using e: IdCounter): CSyntax[Either[X, B]]","d":"ll1compiletime.syntax.SyntaxDefinition","k":"def"},
{"l":"ll1compiletime/syntax/SyntaxDefinition.html#~-cef","e":false,"i":"CSyntax[X]","n":"~","t":"~[B](that: CSyntax[B]): CSyntax[X ~ B]","d":"ll1compiletime.syntax.SyntaxDefinition","k":"def"},
{"l":"ll1compiletime/syntax/SyntaxDefinition.html#~<~-cef","e":false,"i":"CSyntax[X]","n":"~<~","t":"~<~[B](that: CSyntax[B]): CSyntax[X]","d":"ll1compiletime.syntax.SyntaxDefinition","k":"def"},
{"l":"ll1compiletime/syntax/SyntaxDefinition.html#~>~-cef","e":false,"i":"CSyntax[X]","n":"~>~","t":"~>~[B](that: CSyntax[B]): CSyntax[B]","d":"ll1compiletime.syntax.SyntaxDefinition","k":"def"}];